# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_make', models.CharField(max_length=25)),
                ('car_model', models.CharField(max_length=25)),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=10)),
                ('min_price', models.IntegerField(default=0)),
                ('max_price', models.IntegerField(default=0)),
                ('min_kms', models.IntegerField(default=0)),
                ('max_kms', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('ACT', 'ACT'), ('New South Wales', 'New South Wales'), ('Northern Territory', 'Northern Territory'), ('Queensland', 'Queensland'), ('South Australia', 'South Australia'), ('Tasmania', 'Tasmania'), ('Victoria', 'Victoria'), ('Western Australia', 'Western Australia')], max_length=25)),
            ],
        ),
    ]
