# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsales_calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('kms', models.IntegerField(default=0)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carsales_calc.Search')),
            ],
        ),
    ]
