# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsales_calc', '0002_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='link',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
